site_name: 2020_5DI_Team2
nav:
    - 'Project Charter': 'projectcharter.md'
    - 'Project Charter PDF': 'projectcharter.pdf'
    - 'Software Requirements Specification': 'softwarerequirementsspecification.md'
    - 'Software Requirements Specification PDF': 'requirementsspecifications.pdf'
    - 'Software Project Management Plan': 'softwareprojectmanagementplan.md'
    - 'Software Project Management Plan PDF': 'softwareprojectmanagementplan.pdf'
    - 'Business Model Canvas PDF': 'businessmodelcanvas.pdf'
    - 'Project Model Canvas PDF': 'projectmodelcanvas.pdf'
    - 'Release Plan': 'releaseplan.md'
    - 'Release Plan PDF': 'releaseplan.pdf'
    - 'Iteration Plan': 'iterationplan.md'
    - 'Iteration Plan PDF': 'iterationplan.pdf'
    - 'Test Plan': 'testplan.md'
    - 'Test Plan PDF': 'testplan.pdf'
    - 'User Guide': 'userguide.md'
    - 'User Guide PDF': 'userguide.pdf'
    - 'Memorandum of Understanding': 'mou.md'
    - 'Memorandum of Understaning PDF': 'mou.pdf'
    - 'Architecture Design Coding Standards': 'architecturedesigncodingstandards.md'
    - 'Architecture Design Coding Standards PDF': 'architecturedesigncodingstandards.pdf'
    - 'Project Success Criteria': 'projectsuccesscriteria.md'
    - 'Project Success Criteria PDF': 'projectsuccesscriteria.pdf'
    - 'Test Case Specification': 'testcasespecification.md'
    - 'Test Case Specification PDF': 'testcasespecification.pdf'
    - 'System Documentation': 'systemdocumentation.md'
    - 'System Documentation PDF': 'systemdocumentation.pdf'
    - 'Data Processing Agreement': 'dpa.md'
    - 'Data Processing Agreement PDF': 'dpa.pdf'

    
theme:
    name: readthedocs

