site_name: 2020_5DI_Team2
nav:
    - 'Project Charter': 'projectcharter.md'
    - 'Software Requirements Specification': 'softwarerequirementsspecification.md'
    - 'Software Project Management Plan': 'softwareprojectmanagementplan.md'
    - 'Business Model Canvas': 'businessmodelcanvas.pdf'
    - 'Business Model Canvas': 'businessmodelcanvas.pdf'
  
    
theme:
    name: readthedocs

