site_name: 2020_5DI_Team2
nav:
    - 'Project Charter': 'projectcharter.md'
    - 'Software Requirements Specification': 'softwarerequirementsspecification.md'
    - 'Software Project Management Plan': 'softwareprojectmanagementplan.md'
    - 'Project Charter 2': 'projectcharter2.md'
  
    
theme:
    name: readthedocs

use_directory_urls: true
