site_name: 2020_5DI_Team2
nav:
    - 'Project Charter': 'projectcharter.md'
    - 'Project Charter': 'projectcharter.pdf'
    - 'Software Requirements Specification': 'softwarerequirementsspecification.md'
    - 'Software Requirements Specification': 'softwarerequirementsspecification.pdf'
    - 'Software Project Management Plan': 'softwareprojectmanagementplan.md'
    - 'Software Project Management Plan': 'softwareprojectmanagementplan.pdf'
    - 'Business Model Canvas': 'businessmodelcanvas.pdf'
    - 'Project Model Canvas': 'projectmodelcanvas.pdf'
    - 'Release Plan': 'releaseplan.md'
    - 'Release Plan': 'releaseplan.pdf'
    - 'Iteration Plan': 'iterationplan.md'
    - 'Iteration Plan': 'iterationplan.pdf'
    - 'Test Plan': 'testplan.md'
    - 'Test Plan': 'testplan.pdf'
    - 'User Guide': 'userguide.md'
    - 'User Guide PDF': 'userguide.pdf'
    - 'Memorandum of Understanding': 'mou.md'
    - 'Memorandum of Understaning PDF': 'mou.pdf'
    - 'Architecture Design Coding Standards': 'architecturedesigncodingstandards.md'
    - 'Architecture Design Coding Standards': 'architecturedesigncodingstandards.pdf'
    - 'Project Success Criteria': 'projectsuccesscriteria.md'
    - 'Project Success Criteria': 'projectsuccesscriteria.pdf'
    - 'Test Case Specification': 'testcasespecification.md'
    - 'Test Case Specification': 'testcasespecification.pdf'
    - 'System Documentation': 'systemdocumentatio.md'
    - 'System Documentation': 'systemdocumentationn.pdf'

    
theme:
    name: readthedocs

